In [2]:
# %pip install pandas

Collecting pandas
  Downloading pandas-3.0.2-cp314-cp314-macosx_11_0_arm64.whl.metadata (79 kB)
Collecting numpy>=2.3.3 (from pandas)
  Downloading numpy-2.4.4-cp314-cp314-macosx_14_0_arm64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/l.tereshchenkova/.local/share/virtualenvs/barko-docs-6W2yjPqi/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/l.tereshchenkova/.local/share/virtualenvs/barko-docs-6W2yjPqi/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.2-cp314-cp314-macosx_11_0_arm64.whl (9.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 941.0 kB/s  0:00:11 eta 0:00:01
Downloading numpy-2.4.4-cp314-cp314-macosx_14_0_arm64.whl (5.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.2/5.2 MB 417.4 kB/s  0:00:11 eta 0:00:01
Installing collected packages: numpy, pandas
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [pandas]2m1/2 [pandas]
Successfully installed numpy-2.4.4 pandas-3.0.2

[notice] A new release of pip is available: 26.0.1 -> 26.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd

In [7]:
dogs = pd.read_csv('dogs.csv')
adoptions = pd.read_csv('adoptions.csv')

In [8]:
dogs.head()

,name,link,поступление,id,последнее_сообщение
0,ТРЕФ,https://helpdog.ru/forum/threads/tref-tuapse-s...,сообщение 2023-10-08: Расход Обработка при пос...,16088,https://helpdog.ru/forum/threads/tref-tuapse-s...
1,ЛАТТЕ,https://helpdog.ru/forum/threads/latte-lytkino...,сообщение 2021-05-30: Передержка с 31.05.21 по...,15099,https://helpdog.ru/forum/threads/latte-lytkino...
2,ВОКЕР,https://helpdog.ru/forum/threads/voker-vladika...,сообщение 2023-12-29: 16356/#post-725065 Итого...,16141,https://helpdog.ru/forum/threads/voker-vladika...
3,ОСКАР,https://helpdog.ru/forum/threads/oskar-kurskaj...,сообщение 2025-05-27: Передержка с 26.05.25 по...,16374,https://helpdog.ru/forum/threads/oskar-kurskaj...
4,ТАКЕШИ,https://helpdog.ru/forum/threads/takeshi-turci...,сообщение 2022-03-07: Передержка с 20.10.22 по...,15550,https://helpdog.ru/forum/threads/takeshi-turci...

In [9]:
adoptions.head()

,dog_id,shelter_started_at,home_started_at,back_shelter_at,пристройство,возврат
0,16088,2023-10-09,2025-05-19,NaN,сообщение 2025-05-19: Треф поехал домой,NaN
1,15099,2021-05-31,2026-04-18,2026-04-27,сообщение 2026-04-18: Латте поехал домой,сообщение 2026-04-27: Латте снова в приюте Лат...
2,16141,2023-12-28,NaN,NaN,NaN,NaN
3,16374,2025-05-26,2025-06-24,2026-04-14,сообщение 2025-06-24: Оскар поехал домой,сообщение 2026-04-14: Оскара сегодня вернули в...
4,15550,2022-10-20,2026-04-18,NaN,сообщение 2026-04-18: Такеши поехал домой,NaN

In [10]:
print('Количество собак на форуме:', dogs.shape[0])

Количество собак на форуме: 90

In [11]:
df_home = adoptions[~adoptions['home_started_at'].isnull()].copy()
print('Количество собак, которые были пристроены 1 или более раз:', df_home['dog_id'].unique().shape[0])

Количество собак, которые были пристроены 1 или более раз: 46

In [12]:
# удаляем записи с пустым полем "дата возвращения в приют", оставляем только последнее пристройство без даты "дата возвращения в приют"
for dog_id in df_home['dog_id'].value_counts().items():
    dog_hist = df_home[df_home['dog_id'] == dog_id[0]].copy()
    last_home_date = dog_hist['home_started_at'].max()
    inx_to_drop = dog_hist[(dog_hist['back_shelter_at'].isnull()) & (dog_hist['home_started_at'] != last_home_date)].index.values
    df_home.drop(index=inx_to_drop, inplace=True)

In [13]:
df_home

,dog_id,shelter_started_at,home_started_at,back_shelter_at,пристройство,возврат
0,16088,2023-10-09,2025-05-19,NaN,сообщение 2025-05-19: Треф поехал домой,NaN
1,15099,2021-05-31,2026-04-18,2026-04-27,сообщение 2026-04-18: Латте поехал домой,сообщение 2026-04-27: Латте снова в приюте Лат...
3,16374,2025-05-26,2025-06-24,2026-04-14,сообщение 2025-06-24: Оскар поехал домой,сообщение 2026-04-14: Оскара сегодня вернули в...
4,15550,2022-10-20,2026-04-18,NaN,сообщение 2026-04-18: Такеши поехал домой,NaN
5,16412,2025-12-13,2026-03-22,NaN,сообщение 2026-03-22: Абелла поехала домой,NaN
6,14438,2020-09-15,2021-10-30,2023-12-29,сообщение 2021-10-30: РИКАРДО поехал домой,сообщение 2023-12-29: Рикардо вернулся в приют
7,16058,2023-08-14,2026-04-24,NaN,сообщение 2026-04-24: Сладкий пирожок поехал д...,NaN
8,16022,2023-06-30,2024-03-30,2024-04-01,сообщение 2024-03-30: Бутуз поехал домой,NaN
9,16022,2023-06-30,2025-01-04,2025-01-08,сообщение 2025-01-04: Бутуз поехал домой,сообщение 2025-01-08: Бутуз вернулся в приют( ...
12,16243,2024-05-12,2025-08-13,NaN,сообщение 2025-08-13: Орион поехал домой,NaN
13,14433,2020-03-30,2020-05-31,2023-10-21,сообщение 2020-05-31: Винсент поехал домой. Уд...,сообщение 2023-10-21: спустя 3 года дома верну...
15,8886,2015-04-26,2015-08-22,2015-08-31,сообщение 2015-08-22: (ИСПЫТАТЕЛЬНЫЙ) Горец се...,"сообщение 2015-08-31: Имя двоякое, всяких люде..."
21,16265,2024-06-07,2026-04-18,NaN,сообщение 2026-04-18: Рассел поехал домой,NaN
22,14039,2023-07-02,2026-03-29,NaN,заголовок темы: РИДДИК - ЧЕРНЫЙ КРАСАВЧИК! СЫН...,NaN
27,13149,2018-05-09,2023-01-18,2023-01-19,сообщение 2023-01-18: Юкка поехала домой,сообщение 2023-01-19: Возврат.
28,13149,2018-05-09,2024-01-21,NaN,сообщение 2024-01-21: Юкка поехала домой,NaN
31,14611,2020-07-06,2023-07-10,2023-09-08,сообщение 2023-07-10: Ярил уже полгода вроде к...,сообщение 2023-09-08: Волею судьбы Яричка опят...
33,14909,2021-01-22,2021-05-16,2021-06-23,сообщение 2021-05-16: Люцик поехал домой￼,сообщение 2021-06-23: Неужели проблема со здор...
36,14909,2021-01-22,2022-06-14,2022-09-21,сообщение 2022-06-14: Люцерн поехал домой. Пус...,"сообщение 2022-09-21: - пишут, что все хорошо ..."
37,14909,2021-01-22,2023-05-12,2023-05-29,сообщение 2023-05-12: Люцерн поехал домой,"сообщение 2023-05-29: Тут было ясно сразу, что..."
38,14909,2021-01-22,2024-02-15,NaN,сообщение 2024-02-15: Люцерн поехал домой,NaN
43,16250,2024-05-26,2024-09-27,2025-01-05,сообщение 2024-09-27: Дукалис поехал домой,NaN
44,16114,2023-11-19,2025-05-02,NaN,сообщение 2025-05-02: Гермес поехал домой,NaN
47,16050,2023-08-30,2024-06-24,NaN,сообщение 2024-06-24: Якобс поехал домой,NaN
49,14839,2020-11-28,2021-10-31,2021-11-21,сообщение 2021-10-31: Тэги поехал домой. Удачи...,NaN
50,15627,2022-05-09,2023-10-29,2024-09-16,сообщение 2023-10-29: Шейна поехала домой,сообщение 2024-09-16: Собаку вернули в приют. ...
51,15627,2022-05-09,2025-09-09,NaN,сообщение 2025-09-09: Шейна поехала домой под ...,NaN
55,15121,2021-06-13,2026-04-20,NaN,сообщение 2026-04-20: Белый Бим поехал домой,NaN
57,14671,2020-08-15,2021-05-11,NaN,"сообщение 2021-05-11: Для того , чтобы собака ...",NaN
59,16100,2023-10-30,2023-12-27,NaN,сообщение 2023-12-27: Чешира поехала домой,NaN
60,15902,2023-02-12,2023-04-12,2024-11-29,сообщение 2023-04-12: Орейра поехала домой,сообщение 2024-11-29: Орейра вернулась в приют...
61,15902,2023-02-12,2025-01-22,NaN,сообщение 2025-01-22: Орейра поехала домой,NaN
64,14181,2019-11-17,2022-07-30,NaN,сообщение 2022-07-30: Яджер уехал домой. С кем...,NaN
66,14385,2020-02-19,2021-05-08,2026-02-18,сообщение 2021-05-08: Малина уехала домой к Ка...,сообщение 2026-02-18: Вчера Малина вернулась в...
69,14220,2019-12-01,2021-10-28,2021-11-05,сообщение 2021-10-28: Рокет поехал домой. Удач...,сообщение 2021-11-05: А причина возврата какая...
72,15291,2021-10-01,2022-05-12,2022-09-25,NaN,сообщение 2022-09-25: Сегодня Басэма вернули в...
74,15964,2023-04-09,2023-09-23,2024-02-17,сообщение 2023-09-23: Гром поехал домой,NaN
76,16390,2025-08-17,2025-10-25,NaN,сообщение 2025-10-25: Аделина поехала домой,NaN
77,16223,2024-04-25,2024-07-10,NaN,сообщение 2024-07-10: Батлер поехал домой,NaN
81,15588,2022-04-04,2022-04-11,NaN,сообщение 2022-04-11: Ясир поехал домой. Удачи...,NaN
90,13889,2021-01-01,2022-01-13,2022-01-23,"сообщение 2022-01-13: Тихонечко, затаив дыхани...",NaN
93,15298,2021-10-01,2022-11-05,2022-11-25,сообщение 2022-11-05: Кромвель поехал домой,NaN
94,15298,2021-10-01,2022-12-08,2023-09-21,сообщение 2022-12-08: Кромвель поехал домой,NaN
95,15557,2022-03-20,2023-07-22,NaN,сообщение 2023-07-22: Наскар поехал домой,NaN
96,13032,2020-01-01,2020-10-04,2021-04-20,сообщение 2020-10-04: Сонет поехал домой. Удач...,сообщение 2021-04-20: И потом бах и возврат.
100,14855,2020-12-11,2022-02-19,NaN,сообщение 2022-02-26: 19.02.2022 Дизелек уехал...,NaN
104,16217,2024-04-12,2024-09-21,2024-12-30,сообщение 2024-09-21: Пресли поехал домой,"сообщение 2024-12-30: К сожалению, не могу ска..."
106,15594,2022-04-08,2024-09-26,2024-11-12,сообщение 2024-09-26: Делона поехала домой - Y...,сообщение 2024-11-12: Делоночка вернулась в пр...
108,15177,2021-07-15,2023-05-18,NaN,сообщение 2023-05-18: Тодин поехал домой,NaN
111,15735,2022-08-05,2022-08-16,2025-05-03,сообщение 2022-08-16: Ярни поехал домой под бо...,NaN
115,15595,2022-04-08,2023-08-05,2023-08-21,сообщение 2023-08-05: Данди поехал домой,сообщение 2023-08-21: Мне хотелось бы знать ре...
116,14701,2020-09-01,2021-06-27,NaN,сообщение 2021-06-27: Даллас поехал домой. Уда...,NaN
117,14598,2020-01-20,2020-09-27,2021-01-20,сообщение 2020-09-27: ВАШИНГТОН поехал домой У...,"сообщение 2021-01-20: Мне очень не нравится, к..."
121,15480,2022-01-28,2024-04-07,2024-08-03,сообщение 2024-04-07: Тайрес поехал домой,"сообщение 2024-08-03: В чем причина возврата, ..."

In [15]:
print('Вернули в приют 1 или более раз: ', df_home[~df_home['back_shelter_at'].isnull()]['dog_id'].unique().shape[0])
print('Процент вернувшихся в приют после пристройства:', round(df_home[~df_home['back_shelter_at'].isnull()]['dog_id'].unique().shape[0]/df_home['dog_id'].unique().shape[0]*100), '%')

Вернули в приют 1 или более раз:  26
Процент вернувшихся в приют после пристройства: 57 %