In [1]:
# %pip install pandas

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('forum_data.csv')

In [4]:
df.head()

,name,shelter_started_at,home_started_at,back_shelter_at,link
0,ТРЕФ,2023-10-09,2025-05-19,NaN,https://helpdog.ru/forum/threads/tref-tuapse-s...
1,ЛАТТЕ,2021-05-31,2026-04-18,2026-04-27,https://helpdog.ru/forum/threads/latte-lytkino...
2,ВОКЕР,2023-12-28,NaN,NaN,https://helpdog.ru/forum/threads/voker-vladika...
3,ОСКАР,2025-05-26,2025-06-24,2026-04-14,https://helpdog.ru/forum/threads/oskar-kurskaj...
4,ТАКЕШИ,2022-10-20,2026-04-18,NaN,https://helpdog.ru/forum/threads/takeshi-turci...

In [16]:
print('Количество собак на форуме:', df['link'].unique().shape[0])

Количество собак на форуме: 90

In [17]:
df_home = df[~df['home_started_at'].isnull()].copy()
print('Количество собак, которые были пристроены 1 или более раз:', df_home['link'].unique().shape[0])

Количество собак, которые были пристроены 1 или более раз: 46

In [18]:
# удаляем записи с пустым полем "дата возвращения в приют", оставляем только последнее пристройство без даты "дата возвращения в приют"
for link in df_home['link'].value_counts().items():
    dog_hist = df[df['link'] == link[0]].copy()
    last_home_date = dog_hist['home_started_at'].max()
    inx_to_drop = dog_hist[(dog_hist['back_shelter_at'].isnull()) & (dog_hist['home_started_at'] != last_home_date)].index.values
    df_home.drop(index=inx_to_drop, inplace=True)

In [15]:
df_home

,name,shelter_started_at,home_started_at,back_shelter_at,link
0,ТРЕФ,2023-10-09,2025-05-19,NaN,https://helpdog.ru/forum/threads/tref-tuapse-s...
1,ЛАТТЕ,2021-05-31,2026-04-18,2026-04-27,https://helpdog.ru/forum/threads/latte-lytkino...
3,ОСКАР,2025-05-26,2025-06-24,2026-04-14,https://helpdog.ru/forum/threads/oskar-kurskaj...
4,ТАКЕШИ,2022-10-20,2026-04-18,NaN,https://helpdog.ru/forum/threads/takeshi-turci...
5,АБЕЛЛА,2025-12-13,2026-03-22,NaN,https://helpdog.ru/forum/threads/abella-skital...
6,РИКАРДО,2020-09-15,2021-10-30,2023-12-29,https://helpdog.ru/forum/threads/rikardo-1-god...
7,ТОРС,2023-08-14,2026-04-24,NaN,https://helpdog.ru/forum/threads/tors-vladimir...
8,БУТУЗ,2023-06-30,2024-03-30,2024-04-01,https://helpdog.ru/forum/threads/butuz-vsju-zh...
9,БУТУЗ,2023-06-30,2025-01-04,2025-01-08,https://helpdog.ru/forum/threads/butuz-vsju-zh...
12,ОРИОН,2024-05-12,2025-08-13,NaN,https://helpdog.ru/forum/threads/orion-orexovo...
13,ВИНСЕНТ,2020-03-30,2020-05-31,2023-10-21,https://helpdog.ru/forum/threads/vinsent-nesch...
15,ГОРЕЦ,2015-04-26,2015-08-22,2015-08-31,https://helpdog.ru/forum/threads/gorec-pojman-...
21,РАССЕЛ,2024-06-07,2026-04-18,NaN,https://helpdog.ru/forum/threads/rassel-rostov...
22,РИДДИК,2023-07-02,2026-03-29,NaN,https://helpdog.ru/forum/threads/riddik-cherny...
27,ЮККА,2018-05-09,2023-01-18,2023-01-19,https://helpdog.ru/forum/threads/jukka-schenok...
28,ЮККА,2018-05-09,2024-01-21,NaN,https://helpdog.ru/forum/threads/jukka-schenok...
31,ЯРИЛ,2020-07-06,2023-07-10,2023-09-08,https://helpdog.ru/forum/threads/jaril-jakutsk...
33,ЛЮЦЕРН,2021-01-22,2021-05-16,2021-06-23,https://helpdog.ru/forum/threads/ljucern-kazan...
36,ЛЮЦЕРН,2021-01-22,2022-06-14,2022-09-21,https://helpdog.ru/forum/threads/ljucern-kazan...
37,ЛЮЦЕРН,2021-01-22,2023-05-12,2023-05-29,https://helpdog.ru/forum/threads/ljucern-kazan...
38,ЛЮЦЕРН,2021-01-22,2024-02-15,NaN,https://helpdog.ru/forum/threads/ljucern-kazan...
43,ДУКАЛИС,2024-05-26,2024-09-27,2025-01-05,https://helpdog.ru/forum/threads/dukalis-dubna...
44,ГЕРМЕС,2023-11-19,2025-05-02,NaN,https://helpdog.ru/forum/threads/germes-gruzij...
47,ЯКОБС,2023-08-30,2024-06-24,NaN,https://helpdog.ru/forum/threads/jakobs-istosc...
49,ТЭГИ,2020-11-28,2021-10-31,2021-11-21,https://helpdog.ru/forum/threads/tehgi-tula-nu...
50,ШЕЙНА,2022-05-09,2023-10-29,2024-09-16,https://helpdog.ru/forum/threads/shejna-shatur...
51,ШЕЙНА,2022-05-09,2025-09-09,NaN,https://helpdog.ru/forum/threads/shejna-shatur...
55,БЕЛЫЙ БИМ,2021-06-13,2026-04-20,NaN,https://helpdog.ru/forum/threads/belyj-bim_-ad...
57,БРИОН,2020-08-15,2021-05-11,NaN,https://helpdog.ru/forum/threads/brion-brjansk...
59,ЧЕШИРА,2023-10-30,2023-12-27,NaN,https://helpdog.ru/forum/threads/cheshira-chec...
60,ОРЕЙРА,2023-02-12,2023-04-12,2024-11-29,https://helpdog.ru/forum/threads/orejra-orenbu...
61,ОРЕЙРА,2023-02-12,2025-01-22,NaN,https://helpdog.ru/forum/threads/orejra-orenbu...
64,ЧАРЛИК,2019-11-17,2022-07-30,NaN,https://helpdog.ru/forum/threads/charlik-xozja...
66,МАЛИНА,2020-02-19,2021-05-08,2026-02-18,https://helpdog.ru/forum/threads/malina-sos-so...
69,РОКЕТ,2019-12-01,2021-10-28,2021-11-05,https://helpdog.ru/forum/threads/roket-nashli-...
72,БАСЭМ,2021-10-01,2022-05-12,2022-09-25,https://helpdog.ru/forum/threads/basehm-bobruj...
74,ГРОМ,2023-04-09,2023-09-23,2024-02-17,https://helpdog.ru/forum/threads/grom-amstaff-...
76,АДЕЛИНА,2025-08-17,2025-10-25,NaN,https://helpdog.ru/forum/threads/adelina-molod...
77,БАТЛЕР,2024-04-25,2024-07-10,NaN,https://helpdog.ru/forum/threads/batler-balako...
81,ЯСИР,2022-04-04,2022-04-11,NaN,https://helpdog.ru/forum/threads/jasir-jakutsk...
90,МАРСЕЛЬ,2021-01-01,2022-01-13,2022-01-23,https://helpdog.ru/forum/threads/marsel-privez...
93,КРОМВЕЛЬ,2021-10-01,2022-11-05,2022-11-25,https://helpdog.ru/forum/threads/kromvel-chern...
94,КРОМВЕЛЬ,2021-10-01,2022-12-08,2023-09-21,https://helpdog.ru/forum/threads/kromvel-chern...
95,НАСКАР,2022-03-20,2023-07-22,NaN,https://helpdog.ru/forum/threads/naskar-nalchi...
96,СОНЕТ,2020-01-01,2020-10-04,2021-04-20,https://helpdog.ru/forum/threads/sonet-ryzhij-...
100,ДИЗЕЛЕК,2020-12-11,2022-02-19,NaN,https://helpdog.ru/forum/threads/dizelek-so-sc...
104,ПРЕСЛИ,2024-04-12,2024-09-21,2024-12-30,https://helpdog.ru/forum/threads/presli-nashli...
106,ДЕЛОНА,2022-04-08,2024-09-26,2024-11-12,https://helpdog.ru/forum/threads/delona-doneck...
108,ТОДИН,2021-07-15,2023-05-18,NaN,https://helpdog.ru/forum/threads/todin-turcija...
111,ЯРНИ,2022-08-05,2022-08-16,2025-05-03,https://helpdog.ru/forum/threads/jarni-7-mesja...
115,ДАНДИ,2022-04-08,2023-08-05,2023-08-21,https://helpdog.ru/forum/threads/dandi-doneck-...
116,ДАЛЛАС,2020-09-01,2021-06-27,NaN,https://helpdog.ru/forum/threads/dallas-brosil...
117,ВАШИНГТОН,2020-01-20,2020-09-27,2021-01-20,https://helpdog.ru/forum/threads/vashington-vl...
121,ТАЙРЕС,2022-01-28,2024-04-07,2024-08-03,https://helpdog.ru/forum/threads/tajres-vyveze...

In [26]:
print('Вернули в приют 1 или более раз: ', df_home[~df_home['back_shelter_at'].isnull()]['link'].unique().shape[0])
print('Процент вернувшихся в приют после пристройства:', round(df_home[~df_home['back_shelter_at'].isnull()]['link'].unique().shape[0]/df_home['link'].unique().shape[0]*100), '%')

Вернули в приют 1 или более раз:  26
Процент вернувшихся в приют после пристройства: 57 %